# Generated by Django 5.2.3 on 2025-07-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_userdetails_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='DOB',
            new_name='dob',
        ),
    ]
